### ISSUE TITLE
Less fragmented code

### ISSUE THREAD

**Issue by lieuwex** [tomsmeding/aimaker#8]
Currently we have to define different stuff for functions on many places; arity, required tier. Is it possible to make this info more centralized?

**Comment by tomsmeding** [comment]
I'll look into it for a sec

**Comment by tomsmeding** [comment]
A list of things that relate to instructions:
- `enum Instruction` — namespace Parser, parser.h
- `convertInstruction` and `convertInstructionReverse` (Instruction <-> string) — namespace Parser, parser.cpp
- map `instr_arity_map` — global, parser.cpp (for extern)
- map `instr_tier_map` — global, parameters.cpp (for extern)
- func `instructionWorkTime` — global, parameters.cpp
- the actual implementations — `Bot::executeCurrentLine`, bot.cpp

**Comment by tomsmeding** [comment]
- instr_arity_map really has to go to parameters.cpp. Not sure why it isn't there anyway.
- enum Instruction is now in namespace Parser. It's just a list of the instruction enum entries; we could move it to parameters.cpp for grouping purposes, but that would move it out of namespace Parser. Or we could put it in the namespace anyway. I'm not sure whether to 1. move it to parameters.cpp without leaving namespace Parser, or to 2. leave it where it is for structure to make sense. Because really, having the enum that really belongs to the parser in — wait for it — the _parameters_ file is a bit weird.
- the same goes for `convertInstruction(Reverse)`, really.
- the implementations can't really move, sadly.

@lieuwex, thoughts?

**Comment by tomsmeding** [comment]
https://github.com/aimaker/aimaker/tree/cleanup

**Comment by lieuwex** [comment]
> instr_arity_map really has to go to parameters.cpp. Not sure why it isn't there anyway.

Yes please

> enum Instruction is now in namespace Parser

It's fine where it is now

> the implementations can't really move, sadly.

:(

**Comment by tomsmeding** [comment]
> :(

:(

**Comment by tomsmeding** [comment]
So does anything need to be moved still?

**Comment by lieuwex** [comment]
@tomsmeding I don't think so
